import { z } from "zod";
import { ISO8601TimestampSchema } from "../utils/Timestamp";

/**
 * Message representing a command, query, request, or response between runtimes.
 *
 * Messages are imperative (action-oriented) unlike RuntimeEvent which is declarative (fact-oriented).
 *
 * Common patterns:
 * - **Request**: Sender initiates an action; receiver responds with a reply.
 * - **Notification**: Sender sends a message without expecting a response.
 * - **Streaming**: Multiple messages in sequence with same correlationId.
 *
 * Correlation:
 * - Use `correlationId` to link related messages and responses.
 * - For request-reply, recipient echoes the same `correlationId` in the response.
 * - For streaming, all messages share the same `correlationId`.
 *
 * @property id - Unique message identifier (optional; generated by sender if omitted).
 * @property type - Message type/operation (e.g., "query", "execute", "subscribe").
 * @property payload - Message body; schema depends on message type.
 * @property sender - Identifier of the sending runtime (optional).
 * @property timestamp - ISO 8601 UTC/offset timestamp (optional).
 * @property correlationId - Links related messages and responses.
 *
 * @example
 * ```ts
 * const request: RuntimeMessage = {
 *   id: "msg-123",
 *   type: "query.execute",
 *   payload: { query: "SELECT * FROM users WHERE id = ?", params: [123] },
 *   sender: "client",
 *   timestamp: new Date().toISOString(),
 *   correlationId: "corr-456",
 * };
 * ```
 */
export const RuntimeMessageSchema = z.object({
  id: z.string().optional(),
  type: z.string().min(1, "Message type is required"),
  payload: z.unknown().optional(),
  sender: z.string().optional(),
  timestamp: ISO8601TimestampSchema.optional(),
  correlationId: z.string().optional(),
});

export type RuntimeMessage = z.infer<typeof RuntimeMessageSchema>;

